### ISSUE TITLE
Remove state management from the service

### ISSUE THREAD

**Issue by Primetalk** [cotiviti/service-lifecycle-api#5]
If we separate the `CotivitiService` into two interfaces:

```
interface CotivitiServiceFactory<S extends CotivitiService>{
  S start(String id, Config config);
}
```

and 
```
interface CotivitiService {
    void destroy();
    ServiceStatus getStatus();
}
```

Then we move management of "running" state to the environment. The service implementation doesn't need to worry about that state.

**Comment by Primetalk** [comment]
This reduces the number of statuses:

```
public enum ServiceState {
	RUNNING,  // While it is running.
	STOPPED, // After the program has completed normally.
	ERROR, // When an abnormal exit occurs.
}
```

If we use `Exception`s we may remove `ERROR` because it can be replaced with appropriate `Exception`.

And for the last two states:
```
public enum ServiceState {
	RUNNING,  // While it is running.
	STOPPED, // After the program has completed normally.
}
```
we may either use `Boolean`, or nothing at all, because we may keep that state on the management side.

**Comment by Primetalk** [comment]
If we finally remove any state from the service, we will have very simple interface:

```
interface CotivitiService {
    void destroy();
}
```

We may, however want to `ping` the service for it's status.
```
interface CotivitiServicePolling {
    void ensureIsRunning();
}
```
or we may use some other monitoring means like `MXBean`

**Comment by mykelalvis** [comment]
How you manage things behind this interface is your concern.
I see no actual benefit in splitting it other than an attempt to remove a status that I have indicated I desire in #4

**Comment by Primetalk** [comment]
The implementers of the current interface (vendors of some service) have to:

1. Maintain some state inside a single object `MyServiceImpl` (the configuration, the identification, the running status). So that their implementation is mutable.
2. Consequently, they have to serialize access to the state, because no one guarantees that the methods are called from a single thread. 
3. They have to also maintain inconsistent state of their object between `initialize` and `configure`, because the configuration information is provided to them in two separate calls (`initialize`, `configure`). Why then don't we add another method `preconfigure` that will add yet another step in the configuration process?
4. The service in the state between `initialize` and `configure` cannot be used in any other way except calling `configure` on it. But we have to provide reactions all other methods for the case that they have been called in this inconsistent state. Because the provided interface gives no guarantee that it is called in a particular order.

On the contrary, the proposed two interfaces (factory + service handle):
1. Requires a specific sequence of calls. No one can call any method on a service handle before successfully creating it. So, in the service we may be absolutely sure that all the required configuration steps are done. Successfully.
2. There is no inconsistent state between `initialize` and `configure`. It's a single step. It either succeeds or fails. If it succeeds, we get a service handle that is fully working, configured, and running. We may be absolutely sure in that. If it fails, we cannot do anything with the service because there is no handle to it.
3. Service implementors do not have to maintain access to their state. They simply create an immutable object and return it back.

**Comment by mykelalvis** [comment]
Service implementors *do* have to maintain some reportable version of their state.  That's the nature of a service.  If we were running in AWS Lambda, that would _still_ exist as an aspect of the runtime (much like it does now within the lifecycle api).

The implementor of a service is alway absolutely sure that the required configuration is available becuase they can fail if it is not.

The executor of the service just checks that status.  Thus the actor that know the state of the service can respond with that state, which every service always maintains, and the executor knows what to do with that.
